version: '3.9'
services:
  dev:
    container_name: nginx_nms_ecs_dev
    build:
      context: docker/dev
    platform: linux/amd64
    volumes:
      - './:/var/code'
      - './docker/dev/nginx.conf:/etc/nginx/conf.d/custom.conf:ro'
    working_dir: '/var/code'
    command: [ '/bin/sh', '-c', 'nginx -g "daemon off;"' ]
    env_file:
      - .env
    restart: always
    ports:
      - "8443:8080"
    depends_on:
      - docker

  docker:
    container_name: nginx_nms_ecs_dev_docker
    image: docker:dind
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=
